version: "3"
services:
  php7:
    image: bzrk/php-cli:7.4
    volumes:
      - ./:/root/work
    working_dir: /root/work
    command: composer verify
  php8:
    image: bzrk/php-cli:8.1
    volumes:
      - ./:/root/work
    working_dir: /root/work
    command: composer verify
