name: PHP Composer
on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      matrix:
        php_version: [ 7.4, 8.1 ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Verify
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          extensions: phar
          coverage: none
          tools: composer:v2

      - name: Run composer verify
        run: composer verify